//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpooninDrawer.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpooninDrawer.Content.RStrings", typeof(RStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ControlCancel {
            get {
                return ResourceManager.GetString("ControlCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ControlConfirm {
            get {
                return ResourceManager.GetString("ControlConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string ControlDown {
            get {
                return ResourceManager.GetString("ControlDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string ControlLeft {
            get {
                return ResourceManager.GetString("ControlLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Menu.
        /// </summary>
        internal static string ControlOpenMenu {
            get {
                return ResourceManager.GetString("ControlOpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string ControlPause {
            get {
                return ResourceManager.GetString("ControlPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string ControlRight {
            get {
                return ResourceManager.GetString("ControlRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string ControlUp {
            get {
                return ResourceManager.GetString("ControlUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Luck, Player 1!.
        /// </summary>
        internal static string GoodLuckPlayer1 {
            get {
                return ResourceManager.GetString("GoodLuckPlayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives.
        /// </summary>
        internal static string Lives {
            get {
                return ResourceManager.GetString("Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string SettingsBack {
            get {
                return ResourceManager.GetString("SettingsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        internal static string SettingsBorderlessScreen {
            get {
                return ResourceManager.GetString("SettingsBorderlessScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string SettingsControls {
            get {
                return ResourceManager.GetString("SettingsControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string SettingsFullScreen {
            get {
                return ResourceManager.GetString("SettingsFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Key for .
        /// </summary>
        internal static string SettingsRemapConfirm {
            get {
                return ResourceManager.GetString("SettingsRemapConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string SettingsResolution {
            get {
                return ResourceManager.GetString("SettingsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1920 x 1080.
        /// </summary>
        internal static string SettingsResolution1080 {
            get {
                return ResourceManager.GetString("SettingsResolution1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280 x 720.
        /// </summary>
        internal static string SettingsResolution720 {
            get {
                return ResourceManager.GetString("SettingsResolution720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Settings.
        /// </summary>
        internal static string SettingsScreenSettings {
            get {
                return ResourceManager.GetString("SettingsScreenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string SettingsVolume {
            get {
                return ResourceManager.GetString("SettingsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string SettingsWindowScreen {
            get {
                return ResourceManager.GetString("SettingsWindowScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test String.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Escaped, Congrats!.
        /// </summary>
        internal static string YouEscaped {
            get {
                return ResourceManager.GetString("YouEscaped", resourceCulture);
            }
        }
    }
}
